export const GetUserListsBouchon = () => {
  return [
    {
      _id: '1',
      titre: 'Life goals',
      nombreElements: '10',
      elements: [
        'Buy a house',
        'Get a dream job',
        'Become rich',
        'live healthy',
        'Have children',
        'Buy a Lamborghini',
        'Get a dream body',
        'Buy a house',
        'Get a dream job',
        'Become rich',
        'live healthy',
        'Have children',
        'Buy a Lamborghini',
        'Get a dream body',
      ],
    },
    {
      _id: '2',
      titre: 'Housework',
      nombreElements: '10',
      elements: [
        'Buy a house',
        'Get a dream job',
        'Become rich',
        'live healthy',
        'Have children',
        'Buy a Lamborghini',
        'Get a dream body',
      ],
    },
    {
      _id: '3',
      titre: 'Shopping',
      nombreElements: '10',
      elements: [
        'Buy a house',
        'Get a dream job',
        'Become rich',
        'live healthy',
        'Have children',
        'Buy a Lamborghini',
        'Get a dream body',
      ],
    },
    {
      _id: '4',
      titre: 'Job Calls',
      nombreElements: '10',
      elements: [
        'Buy a house',
        'Get a dream job',
        'Become rich',
        'live healthy',
        'Have children',
        'Buy a Lamborghini',
        'Get a dream body',
      ],
    },
  ];
};
